export const typeTests = [
    {
        title: 'Allergy / Immunology',
        items: [
            'Acetylcholine Receptor Modulating Antibody',
            'Aldolase',
            'Alpha-1-Antitrypsin (AAT) Quantitation and Mutation Analysis',
            'ANA Screen, IFAwith Reflex to Titer and Pattern, IFA',
            'Angiotensin Converting Enzyme (ACE)',
            'Aspergillus Antigen',
            'Celiac Disease Comprehensive Panel, Infant',
            'Celiac Disease Panel',
            'Complement, Total (CH50)',
            'Cyclic Citrullinated Peptide(CCP) AntibodyIgG',
            'IgE',
            'IgG Subclasses Panel',
            'Immune Cell Function',
            'Mycophenolic Acid',
            'Prometheus Serum Infliximab/HACA',
            'Scleroderma Antibody (Scl-70)',
            'Sjogren\'s Antibodies (SS-A, SS-B)',
            'Sm/RNP Antibody',
            'Streptococcus pneumoniae IgG (23 Serotypes), MAID',
            'Tryptase',
            'Tumor Necrosis Factor-Alpha, Highly Sensitive',
        ],
    },
    {
        title: 'Endocrinology',
        items: [
            'Deoxycorticosterone',
            'DHEA (Dehydroepiandrosterone), Unconjugated, LC/MS/MS',
            'DHEA Sulfate, Immunoassay',
            'Estradiol, Ultrasensitive, LC/MS/MS',
            'FSH (Follicle Stimulating Hormone), Pediatrics',
            'Growth Hormone (GH)',
            'Hemoglobin A1c',
            'Homovanillic Acid, 24-Hour Urine with Creatinine',
            'IGF Binding Protein-3 (IGFBP-3)',
            'IGF-I, LC/MS',
            'Inhibin B',
            'Insulin',
            'Islet Cell Antibody Screen with Reflex to Titer',
            'LH, Pediatrics',
            'Metanephrines, Fractionated, Free, LC/MS/MS, Plasma',
            'Osteocalcin, N-MID',
            'Plasma Renin Activity, LC/MS/MS',
            'Pregnenolone, LC/MS/MS',
            'Prolactin',
            'PTH, Intact and Calcium',
            'PTH-Related Protein (PTH-rP)',
            'T 3 Free (FT 3)',
            'T 4 Free, Direct Dialysis',
            'Testosterone, Free and Total, LC/MS/MS',
            'Testosterone, Free, Bioavailable and Total, LC/MS/MS',
            'Testosterone, Total, LC/MS/MS',
            'Thyroglobulin Antibodies',
            'Thyroid Peroxidase Antibodies (TPO)',
            'TSH Receptor Antibody',
            'TSI (Thyroid Stimulating Immunoglobulin)',
            'Vitamin D, 25-Hydroxy, LC/MS/MS',
            'VMA (Vanillylmandelic Acid), 24-Hour Urine',
            'von Willebrand Comprehensive Panel',
        ],
    },
    {
        title: 'Genetics',
        items: [
            'Acylcarnitine, Plasma',
            'Acylglycines, Quantitative, Urine',
            'Amino Acid Analysis, LC/MS, Plasma',
            'Carnitine, LC/MS/MS',
            'Chromosome Analysis, Blood',
            'Chromosome Analysis, Hematologic Malignancy',
            'Chromosome Analysis, High Resolution',
            'Chromosome Analysis, High Resolution',
            'Coenzyme Q10',
            'Cystic Fibrosis Complete Rare Mutation Analysis,',
            'Gene Sequence (NY)',
            'Fatty Acid Profile, Peroxisomal C22-C26',
            'FISH, DiGeorge, Velocardiofacial Syndrome (VCFS)',
            'FISH,Myeloid Lymphoid Leukemia (MLL) (11q23)',
            'Gene Rearrangement',
            'Galactose 1-Phosphate Uridyltransferase',
            'Genomic Alterations, Postnatal, ClariSure Oligo-SNP Array',
            'Genomic Alterations, Postnatal, ClariSure Oligo-SNP Array',
            'HLA Class II DR, DQ, DNA Typing',
            'Homocysteine, Cardiovascular',
            'Inflammatory Bowel Disease Differentiation Panel',
            'Methylenetetrahydrofolate Reductase (MTHFR),',
            'DNA Mutation Analysis',
            'Methylmalonic Acid',
            'Organic Acids, Quantitative, Random Urine, Full Panel',
            'Prader-Willi/Angelman Syndrome, DNA Methylation Analysis',
            'Pyruvic Acid (Pyruvate)',
            'Rett Syndrome Mutation Analysis',
            'Smith-Lemli-Opitz Screen, Plasma',
            'Spinal Muscular Atrophy (SMA) Carrier Screen (Athena 444)',
            'Spinal Muscular Atrophy (SMA) Diagnostic (Athena 111D)',
            'XSense , Fragile X with Reflex',
        ],
    },
    {
        title: 'GI',
        items: [
            'Bile Acids, Fractionated And Total',
            'Calprotectin, Stool',
            'Disaccharidases',
            'Endomysial Antibody Screen (IgA) with Reflex to Titer',
            'Gliadin Antibody (IgG)',
            'Helicobacter pylori Antibodies (IgG, IgA, IgM)',
            'Helicobacter pylori Antigen, EIA, Stool',
            'Lactoferrin, Qualitative, Stool',
            'Lactoferrin, Quantitative, Stool',
            'Liver Kidney Microsomal (LKM-1) Antibody(IgG)',
            'Pancreatic Elastase-1',
            'Thiopurine S-Methyltransferase (TPMT) Genotype',
            'Tissue Transglutaminase (tTG) Antibody (IgG)',
            'TPMT Activity',
        ],
    },
    {
        title: 'Hematology  /Oncology',
        items: [
            'Alpha-Fetoprotein, Tumor Marker',
            'Antiphospholipid Antibody Panel',
            'bcr/abl Gene Rearrangement, Quant, PCR,',
            'Plasma-Based, Leumeta',
            'Beta-2-Glycoprotein I Antibodies (IgG, IgA, IgM)',
            'Cardiolipin Antibodies(IgG, IgM)',
            'CBC (includes Differential and Platelets)',
            'Factor XIII, Functional',
            'FactorV (Leiden) Mutation Analysis',
            'FISH, ALL, Pre-B Panel',
            'Leukemia/Lymphoma Evaluation',
            'Lupus Anticoagulant Evaluation with Reflex',
            'Neutrophil Antibody, Flow Cytometry',
            'Protein C Activity',
            'Protein S Activity',
            'T 3 Total',
            'Transferrin',
        ],
    },
    {
        title: 'Infectious Disease',
        items: [
            'Adenovirus DNA, Qualitative, Real-Time PCR',
            'B.pertussis/parapertussis DNA, Qualitative, Real-Time PCR',
            'Bartonella Species Antibodies (IgG, IgM) with Reflex to Titer',
            'BK Virus DNA, Quantitative Real-Time PCR, Urine',
            'Bordetella pertussis (IgG, IgA)',
            'Borrelia burgdorferi Antibodies, IFA, CSF',
            'Chlamydia trachomatis/ Neisseria gonorrhoeaeDNA, SDA',
            'Culture, Mycobacteria with Fluorochrome Smear',
            'Cytomegalovirus Antibodies (IgG, IgM), ELISA, CSF',
            'Cytomegalovirus DNA, Quantitative, Real-Time PCR',
            'Diphtheria Antitoxoid Antibody',
            'Enterovirus RNA, Qualitative, Real-Time PCR',
            'Epstein Barr Virus DNA, Qualitative, Real-Time PCR',
            'Epstein-Barr Virus Antibody Panel',
            'Epstein-Barr Virus DNA, Quantitative, Real-Time PCR',
            'Haemophilus influenza Type B Antibody (IgG)',
            'Hepatitis A IgM Antibody',
            'Hepatitis B CoreAntibody (IgM)',
            'Hepatitis B Surface Antigenwith Reflex Confirmation',
            'Hepatitis B Virus DNA, Quantitative, Real-Time PCR',
            'Hepatitis C Antibody',
            'Hepatitis C Viral RNA, Quantitative, Real-Time PCR',
            'Hepatitis C Viral RNA,Qualitative, PCR',
            'Hepatitis Panel, Acute with Reflex Confirmation',
            'Herpes Simplex Virus (IgM) Antibody with Reflex toTiter',
            'Herpes Simplex Virus 1 and 2 (IgG),',
            'Type Specific Antibodies',
            'Herpes Simplex Virus, Type 1 & 2 DNA, Quantitative,',
            'Real-Time PCR',
            'Histoplasma Antigen, Urine',
            'HIV Antibody, HIV-1/2, EIA with Reflexes',
            'HIV-1 PhenoSense Comprehensive',
            'HIV-1 RNA, Quantitative, Real-Time PCR',
            'HTLV-I/II Antibody, withReflex to Confirmatory Assay',
            'Measles Antibodies (IgG, IgM)',
            'Mumps Virus Antibodies (IgG, IgM)',
            'Mycobacterium, Blood Culture',
            'Mycoplasma pneumoniae Antibodies (IgG, IgM)',
            'Norovirus RNA, RT-PCR',
            'Ova and Parasites, Stool, Concentrate and',
            'Permanent Smear',
            'Parainfluenza Virus (Types 1, 2 and 3) RNA,',
            'Qualitative Real-Time PCR',
            'Parvovirus B19 Antibodies (IgG, IgM)',
            'Parvovirus B19 DNA, Qualitative, Real-Time PCR',
            'PhenoSense GT',
            'Poliovirus Antibody, Neutralization',
            'Quantiferon TB Gold, (Client Incubated)',
            'Respiratory Virus PCR Panel IV',
            'RubellaAntibody (IgM)',
            'Streptococcus pneumoniae IgG Antibody Panel',
            '(14 Serotypes), MAID',
            'SureSwab, Chlamydia trachomatis/ Neisseria',
            'gonorrhoeae RNA, TMA',
            'Tetanus Antitoxoid Antibody (EIA)',
            'ToxoplasmaAntibody (IgG)',
            'Trofile Co-Receptor Tropism Assay',
            'Varicella-Zoster Virus Antibodies (IgG, IgM)',
            'Vitamin D, 1,25-Dihydroxy, LC/MS/MS',
            'West NileVirus Antibodies (IgG, IgM), ELISA',
        ],
    },
    {
        title: 'Toxicology',
        items: [
            '10-Hydroxycarbazepine',
            'Chromium, Plasma',
            'Copper',
            'Felbamate (Felbatol)',
            'Lamotrigine',
            'Selenium',
            'Topiramate',
            'Zinc',
            'Zonisamide (Zonegran)',
        ],
    },
    {
        title: 'Other Tests',
        items: [
            'Folate, Serum',
            'Levetiracetam (Keppra)',
            'Vitamin A',
            'Vitamin B 12 (Cobalamin)',
            'Vitamin B 6 (Pyridoxine)',
            'Vitamin E (Tocopherol)',
            'Vitamin K',
        ],
    },
]