export const typeTests = [
    {
        title: 'Featured Tests',
        items: [
            'Acanthamoeba and Naegleria Culture',
            'Adenovirus 40-41 Antigens by EIA',
            'Adenovirus by Qualitative PCR',
            'Bartonella Species by PCR',
            'Bordetella pertussis Antibodies, IgA and IgG by ELISA with Reflex to Immunoblot',
            'Bordetella pertussis Antibodies, IgA, IgG, and IgM by ELISA with Reflex to Immunoblot',
            'Bordetella pertussis Antibodies, IgA, IgG, and IgM by Immunoblot',
            'Bordetella pertussis by PCR',
            'Bordetella pertussis/parapertussis by PCR',
            'Borrelia burgdorferi Antibodies, Total by ELISA with Reflex to IgG & IgM by Western Blot (Early Disease)',
            'Chlamydia Pneumoniae by PCR',
            'Chlamydia trachomatis and Neisseria gonorrhoeae by Transcription-Mediated Amplification (TMA)',
            'Chlamydia trachomatis by Transcription-Mediated Amplification (TMA)',
            'Coxsackie A Antibodies (A-2, 4, 7, 9, 10 & 16 Serotypes)',
            'Coxsackie A9 Virus Antibodies by CF',
            'Coxsackie B Virus Antibodies',
            'Cryptosporidium Antigen by EIA',
            'Cystic Respiratory Culture',
            'Cytomegalovirus Antibodies, IgG and IgM',
            'Cytomegalovirus Antiviral Drug Resistance by Sequencing',
            'Cytomegalovirus by PCR',
            'Cytomegalovirus by PCR, Whole Blood or Bone Marrow',
            'Cytomegalovirus by Qualitative PCR, Saliva',
            'Cytomegalovirus Rapid Culture',
            'Cytomegalovirus, Quantitative PCR',
            'Diphtheria, Tetanus, and H. Influenzae b Antibodies, IgG',
            'E. coli Shiga-like Toxin by EIA',
            'Echovirus Antibodies',
            'Enterovirus Detection by RT-PCR',
            'Epstein-Barr Virus Antibody Panel I',
            'Epstein-Barr Virus Antibody Panel II',
            'Epstein-Barr Virus Antibody Testing',
            'Epstein-Barr Virus by PCR',
            'Eye Culture',
            'Giardia Antigen by EIA',
            'Hepatitis A Virus Panel',
            'Hepatitis Panel, Acute with Reflex to HBsAg Confirmation',
            'Hepatitis Virus Testing',
            'Herpes Simplex Type 1 & Type 2 Glycoprotein G-Specific Antibodies, IgG by ELISA (HerpeSelect®)',
            'Herpes Simplex Virus by PCR',
            'Herpes Simplex Virus Type 1 and/or 2 Antibody Testing',
            'Heterophile Antibody (Infectious Mononucleosis) by Latex Agglutination with Reflex to Titer',
            'Heterophile Antibody (Infectious Mononucleosis) by Latex Agglutination, Qualitative',
            'Human Immunodeficiency Virus 1 DNA PCR, Qualitative',
            'Human Immunodeficiency Virus 1 RNA Quantitative Real-Time PCR',
            'Human Immunodeficiency Virus 1, Genotyping',
            'Human Immunodeficiency Virus Type 1 (HIV-1) Antibody with Reflex to Human Immunodeficiency Virus Type 1 (HIV-1) Antibody Confirmation by Western Blot',
            'Influenza A Virus H1/H3 Subtyping by Real-Time RT-PCR',
            'Influenza Virus A & B DFA with Reflex to Influenza Virus A & B Rapid Culture',
            'Measles (Rubeola) Antibodies, IgG and IgM',
            'Measles (Rubeola) Virus Culture',
            'Mumps Virus Antibody Testing',
            'Mumps Virus Antibody, IgM',
            'Mumps Virus Culture',
            'Mumps Virus RNA Qualitative, Real-Time PCR',
            'Mycoplasma pneumoniae by PCR',
            'Neisseria gonorrhoeae by Transcription-Mediated Amplification (TMA)',
            'Norovirus Group 1 and 2 Detection by RT-PCR',
            'Parainfluenza 1-4 by RT-PCR',
            'Parvovirus B 19 Antibodies, IgG and IgM',
            'Parvovirus B 19, by PCR',
            'Pinworm',
            'Respiratory Syncytial Virus DFA',
            'Respiratory Virus Panel by PCR',
            'Respiratory Viruses DFA',
            'Rubella Antibodies, IgG and IgM',
            'Stool Culture and E. coli Shiga-like Toxin by EIA',
            'Streptococcus (Group A) Rapid with Reflex to Culture',
            'Streptococcus Group B by PCR',
            'Streptococcus pneumoniae Antibodies, IgG (14 serotypes)',
            'TORCH Antibodies, IgG',
            'TORCH Antibodies, IgM',
            'Toxoplasma gondii Antibodies, IgG and IgM',
            'Treponema pallidum Antibody, IgM by ELISA',
            'Varicella-Zoster Virus Antibodies, IgG and IgM',
            'Varicella-Zoster Virus by PCR',
            'Varicella-Zoster Virus DFA with Reflex to Varicella-Zoster Virus Culture',
            'West Nile Virus Antibodies, IgG and IgM by ELISA, CSF',
            'West Nile Virus Antibodies, IgG and IgM by ELISA, Serum',
            'West Nile Virus RNA by RT-PCR',
        ]
    },
    {
        title: 'Molecular Infectious Disease Testing',
        items: [
            'Adenovirus by Qualitative PCR',
            'Bartonella Species by PCR',
            'Bordetella pertussis by PCR',
            'Bordetella pertussis/parapertussis by PCR',
            'Chlamydia Pneumoniae by PCR',
            'Chlamydia trachomatis and Neisseria gonorrhoeae by Transcription-Mediated Amplification (TMA)',
            'Chlamydia trachomatis by Transcription-Mediated Amplification (TMA)',
            'Cytomegalovirus Antiviral Drug Resistance by Sequencing',
            'Cytomegalovirus by PCR',
            'Cytomegalovirus by PCR, Whole Blood or Bone Marrow',
            'Cytomegalovirus by Qualitative PCR, Saliva',
            'Cytomegalovirus, Quantitative PCR',
            'Enterovirus Detection by RT-PCR',
            'Epstein-Barr Virus by PCR',
            'Herpes Simplex Virus by PCR',
            'Human Immunodeficiency Virus 1 DNA PCR, Qualitative',
            'Human Immunodeficiency Virus 1 RNA Quantitative Real-Time PCR',
            'Human Immunodeficiency Virus 1, Genotyping',
            'Influenza A Virus H1/H3 Subtyping by Real-Time RT-PCR',
            'Mumps Virus RNA Qualitative, Real-Time PCR',
            'Mycoplasma pneumoniae by PCR',
            'Neisseria gonorrhoeae by Transcription-Mediated Amplification (TMA)',
            'Norovirus Group 1 and 2 Detection by RT-PCR',
            'Parainfluenza 1-4 by RT-PCR',
            'Parvovirus B 19, by PCR',
            'Respiratory Virus Panel by PCR',
            'Streptococcus Group B by PCR',
            'Varicella-Zoster Virus by PCR',
            'West Nile Virus RNA by RT-PCR',
        ]
    },
    {
        title: 'Bacteriology/Virology',
        items: [
            'Cystic Respiratory Culture',
            'Cytomegalovirus Rapid Culture',
            'E. coli Shiga-like Toxin by EIA',
            'Eye Culture',
            'Influenza Virus A & B DFA with Reflex to Influenza Virus A & B Rapid Culture',
            'Measles (Rubeola) Virus Culture',
            'Mumps Virus Culture',
            'Respiratory Syncytial Virus DFA',
            'Respiratory Viruses DFA',
            'Stool Culture and E. coli Shiga-like Toxin by EIA',
            'Streptococcus (Group A) Rapid with Reflex to Culture',
            'Varicella-Zoster Virus DFA with Reflex to Varicella-Zoster Virus Culture',
        ]
    },
    {
        title: 'Parasitology',
        items: [
            'Acanthamoeba and Naegleria Culture',
            'Adenovirus 40-41 Antigens by EIA',
            'Cryptosporidium Antigen by EIA',
            'Giardia Antigen by EIA',
            'Pinworm',
        ]
    },
    {
        title: 'Serology',
        items: [
            'Bordetella pertussis Antibodies, IgA and IgG by ELISA with Reflex to Immunoblot',
            'Bordetella pertussis Antibodies, IgA, IgG, and IgM by ELISA with Reflex to Immunoblot',
            'Bordetella pertussis Antibodies, IgA, IgG, and IgM by Immunoblot',
            'Borrelia burgdorferi Antibodies, Total by ELISA with Reflex to IgG & IgM by Western Blot (Early Disease)',
            'Coxsackie A Antibodies (A-2, 4, 7, 9, 10 & 16 Serotypes)',
            'Coxsackie A9 Virus Antibodies by CF',
            'Coxsackie B Virus Antibodies',
            'Cytomegalovirus Antibodies, IgG and IgM',
            'Diphtheria, Tetanus, and H. Influenzae b Antibodies, IgG',
            'Echovirus Antibodies',
            'Epstein-Barr Virus Antibody Panel I',
            'Epstein-Barr Virus Antibody Panel II',
            'Epstein-Barr Virus Antibody Testing',
            'Hepatitis A Virus Panel',
        ]
    },
]