export const typeTests = [
    'Allergen Panel, IgE by ImmunoCap ISAC',
    'Allergen, Drugs, Amoxicillin',
    'Allergen, Drugs, Ampicillin',
    'Allergen, Drugs, Penicillin G (major)',
    'Allergen, Drugs, Penicillin V (minor)',
    'Allergen, Epidermals and Animal Proteins, Australian Parrot Droppings IgE',
    'Allergen, Epidermals and Animal Proteins, Budgerigar Droppings (Parakeet)',
    'Allergen, Epidermals and Animal Proteins, Cat Dander',
    'Allergen, Epidermals and Animal Proteins, Chicken Feathers',
    'Allergen, Epidermals and Animal Proteins, Cow Hair and Dander',
    'Allergen, Epidermals and Animal Proteins, Dog Dander',
    'Allergen, Epidermals and Animal Proteins, Duck Feathers IgE',
    'Allergen, Epidermals and Animal Proteins, Feather Mix',
    'Allergen, Epidermals and Animal Proteins, Goat Epithelium IgE',
    'Allergen, Epidermals and Animal Proteins, Goose Feathers',
    'Allergen, Epidermals and Animal Proteins, Guinea Pig Epithelium IgE',
    'Allergen, Epidermals and Animal Proteins, Hamster Epithelium',
    'Allergen, Epidermals and Animal Proteins, Horse Hair and Dander',
    'Allergen, Epidermals and Animal Proteins, Mouse Epithelium',
    'Allergen, Epidermals and Animal Proteins, Mouse Urine IgE',
    'Allergen, Epidermals and Animal Proteins, Parakeet Feathers (Budgerigar)',
    'Allergen, Epidermals and Animal Proteins, Pig (Swine) Epithelium IgE',
    'Allergen, Epidermals and Animal Proteins, Rabbit Epithelium',
    'Allergen, Epidermals and Animal Proteins, Rat Epithelium IgE',
    'Allergen, Epidermals and Animal Proteins, Rat Urine IgE',
    'Allergen, Epidermals and Animal Proteins, Sheep Epithelium/Wool',
    'Allergen, Food, Almond',
    'Allergen, Food, Almond IgG',
    'Allergen, Food, Alpha-Gal (galactose-alpha-1,3-galactose) IgE',
    'Allergen, Food, Alpha-Gal (galactose-alpha-1,3-galactose) Panel',
    'Allergen, Food, Alpha-Lactalbumin',
    'Allergen, Food, Anchovy IgE',
    'Allergen, Food, Annatto Seed IgE',
    'Allergen, Food, Apple',
    'Allergen, Food, Apricot',
    'Allergen, Food, Artichoke IgE',
    'Allergen, Food, Asparagus IgE',
    'Allergen, Food, Avocado',
    'Allergen, Food, Avocado IgG',
    'Allergen, Food, Baker\'s Yeast IgG',
    'Allergen, Food, Baker\'s Yeast/Brewer\'s Yeast',
    'Allergen, Food, Banana',
    'Allergen, Food, Banana IgG',
    'Allergen, Food, Barley',
    'Allergen, Food, Barley IgG',
    'Allergen, Food, Basil IgE',
    'Allergen, Food, Bass Black IgE',
    'Allergen, Food, Bay Leaf IgE',
    'Allergen, Food, Beef',
    'Allergen, Food, Beef IgG',
    'Allergen, Food, Beet Root IgE',
    'Allergen, Food, Beta-Lactoglobulin',
    'Allergen, Food, Black Bean IgE',
    'Allergen, Food, Black Olive IgE',
    'Allergen, Food, Black Pepper',
    'Allergen, Food, Blackberry IgE',
    'Allergen, Food, Blue Mussel',
    'Allergen, Food, Blueberry',
    'Allergen, Food, Brazil Nut',
    'Allergen, Food, Broccoli',
    'Allergen, Food, Broccoli IgG',
    'Allergen, Food, Buckwheat IgE (Fagopyrum esculentum)',
    'Allergen, Food, Cabbage',
    'Allergen, Food, Canola (Rapeseed) Oil IgE',
    'Allergen, Food, Caraway Seed IgE',
    'Allergen, Food, Cardamom Seed IgE',
    'Allergen, Food, Carob Gum/Locust Bean IgE',
    'Allergen, Food, Carrot',
    'Allergen, Food, Casein',
    'Allergen, Food, Casein (Cow\'s Milk) IgG',
    'Allergen, Food, Cashew',
    'Allergen, Food, Cashew IgG',
    'Allergen, Food, Catfish IgE',
    'Allergen, Food, Cauliflower IgE',
    'Allergen, Food, Celery',
    'Allergen, Food, Cheddar Cheese IgG',
    'Allergen, Food, Cheese Mold',
    'Allergen, Food, Cheese Mold IgG',
    'Allergen, Food, Cheese, Cheddar',
    'Allergen, Food, Cherry IgE',
    'Allergen, Food, Chestnut',
    'Allergen, Food, Chicken',
    'Allergen, Food, Chicken IgG',
    'Allergen, Food, Chickpea (Garbanzo Bean) IgE',
    'Allergen, Food, Chocolate',
    'Allergen, Food, Chocolate IgG',
    'Allergen, Food, Cinnamon',
    'Allergen, Food, Clam',
    'Allergen, Food, Clam IgG',
    'Allergen, Food, Clove IgE',
    'Allergen, Food, Coconut',
    'Allergen, Food, Coconut IgG',
    'Allergen, Food, Codfish IgE',
    'Allergen, Food, Coffee',
    'Allergen, Food, Coffee IgG',
    'Allergen, Food, Common Millet IgE',
    'Allergen, Food, Coriander/Cilantro IgE',
    'Allergen, Food, Corn',
    'Allergen, Food, Corn IgG',
    'Allergen, Food, Crab',
    'Allergen, Food, Crab IgG',
    'Allergen, Food, Cranberry IgE',
    'Allergen, Food, Crayfish IgE',
    'Allergen, Food, Cucumber IgE',
    'Allergen, Food, Currant Red, IgE',
    'Allergen, Food, Dill IgE',
    'Allergen, Food, Egg White',
    'Allergen, Food, Egg White IgG',
    'Allergen, Food, Egg Whole',
    'Allergen, Food, Egg Yolk',
    'Allergen, Food, Egg Yolk IgG',
    'Allergen, Food, Eggplant',
    'Allergen, Food, Flaxseed/Linseed IgE',
    'Allergen, Food, Garlic',
    'Allergen, Food, Garlic IgG',
    'Allergen, Food, Gelatin Bovine IgE',
    'Allergen, Food, Gelatin Porcine IgE',
    'Allergen, Food, Ginger IgE',
    'Allergen, Food, Gluten',
    'Allergen, Food, Gluten IgG',
    'Allergen, Food, Goat Milk IgE',
    'Allergen, Food, Grape',
    'Allergen, Food, Grapefruit',
    'Allergen, Food, Green Bean (String) IgE',
    'Allergen, Food, Guar Gum IgE',
    'Allergen, Food, Gulf Flounder IgE',
    'Allergen, Food, Haddock IgE',
    'Allergen, Food, Halibut',
    'Allergen, Food, Hazelnut (Filbert)',
    'Allergen, Food, Herring IgE',
    'Allergen, Food, Honey IgE',
    'Allergen, Food, Honeydew Melon/Cantaloupe',
    'Allergen, Food, Hops',
    'Allergen, Food, Kidney Bean',
    'Allergen, Food, Kiwi',
    'Allergen, Food, Lamb',
    'Allergen, Food, Lemon',
    'Allergen, Food, Lentil',
    'Allergen, Food, Lettuce',
    'Allergen, Food, Lettuce IgG',
    'Allergen, Food, Lima Bean/White Bean',
    'Allergen, Food, Lime IgE',
    'Allergen, Food, Lobster',
    'Allergen, Food, Lobster IgG',
    'Allergen, Food, Macadamia Nut IgE',
    'Allergen, Food, Mackerel',
    'Allergen, Food, Mahi Mahi IgE',
    'Allergen, Food, Malt',
    'Allergen, Food, Malt IgG',
    'Allergen, Food, Mandarin IgE',
    'Allergen, Food, Mango',
    'Allergen, Food, Milk (Boiled) IgE',
    'Allergen, Food, Milk (Cow\'s)',
    'Allergen, Food, Milk (Cows) Components IgE',
    'Allergen, Food, Milk (Sheep), IgE',
    'Allergen, Food, Mint IgE',
    'Allergen, Food, Mushroom',
    'Allergen, Food, Mushroom IgG',
    'Allergen, Food, Mustard',
    'Allergen, Food, Navy Bean',
    'Allergen, Food, Nectarine IgE',
    'Allergen, Food, Nutmeg IgE',
    'Allergen, Food, Oat',
    'Allergen, Food, Oat IgG',
    'Allergen, Food, Octopus IgE (Temporary Referral as of 04/20/17)',
    'Allergen, Food, Olives IgG',
    'Allergen, Food, Onion',
    'Allergen, Food, Onion IgG',
    'Allergen, Food, Orange',
    'Allergen, Food, Orange IgG',
    'Allergen, Food, Oregano IgE',
    'Allergen, Food, Orris Root IgE',
    'Allergen, Food, Ovalbumin IgE',
    'Allergen, Food, Ovomucoid IgE',
    'Allergen, Food, Oyster',
    'Allergen, Food, Oyster IgG',
    'Allergen, Food, Papaya',
    'Allergen, Food, Parsley',
    'Allergen, Food, Pea',
    'Allergen, Food, Peach',
    'Allergen, Food, Peanut',
    'Allergen, Food, Peanut Components IgE',
    'Allergen, Food, Peanut IgG',
    'Allergen, Food, Pear',
    'Allergen, Food, Pecan',
    'Allergen, Food, Pepper C. annuum IgE',
    'Allergen, Food, Pepper C. frutescens IgE',
    'Allergen, Food, Perch IgE',
    'Allergen, Food, Pine (Pinon) Nut',
    'Allergen, Food, Pineapple',
    'Allergen, Food, Pineapple IgG',
    'Allergen, Food, Pistachio',
    'Allergen, Food, Plaice IgE',
    'Allergen, Food, Plum',
    'Allergen, Food, Poppy Seed IgE',
    'Allergen, Food, Pork',
    'Allergen, Food, Pork IgG',
    'Allergen, Food, Potato',
    'Allergen, Food, Potato (White) IgG',
    'Allergen, Food, Pumpkin IgE',
    'Allergen, Food, Pumpkin Seed IgE',
    'Allergen, Food, Quinoa IgE',
    'Allergen, Food, Raspberry IgE',
    'Allergen, Food, Red Dye/Carmine (Red 4) IgE',
    'Allergen, Food, Red Snapper IgE',
    'Allergen, Food, Rice',
    'Allergen, Food, Rice IgG',
    'Allergen, Food, Rye',
    'Allergen, Food, Rye IgG',
    'Allergen, Food, Safflower IgE',
    'Allergen, Food, Sage IgE',
    'Allergen, Food, Salmon',
    'Allergen, Food, Sardine IgE',
    'Allergen, Food, Scallop',
    'Allergen, Food, Scallop IgG',
    'Allergen, Food, Sesame Seed',
    'Allergen, Food, Shrimp',
    'Allergen, Food, Shrimp IgG',
    'Allergen, Food, Sole IgE',
    'Allergen, Food, Soybean',
    'Allergen, Food, Soybean IgG',
    'Allergen, Food, Spinach',
    'Allergen, Food, Squid IgE',
    'Allergen, Food, Strawberry',
    'Allergen, Food, Strawberry IgG',
    'Allergen, Food, Sugar Beet IgE',
    'Allergen, Food, Sugar Cane IgE',
    'Allergen, Food, Sugar Cane IgG4',
    'Allergen, Food, Summer Squash IgE',
    'Allergen, Food, Sunflower Seed IgE',
    'Allergen, Food, Sweet Potato IgE',
    'Allergen, Food, Swordfish IgE',
    'Allergen, Food, Tea',
    'Allergen, Food, Thyme IgE',
    'Allergen, Food, Tilapia IgE',
    'Allergen, Food, Tomato',
    'Allergen, Food, Trout',
    'Allergen, Food, Tuna',
    'Allergen, Food, Tuna IgG',
    'Allergen, Food, Turkey',
    'Allergen, Food, Turkey IgG',
    'Allergen, Food, Turmeric IgE',
    'Allergen, Food, Vanilla',
    'Allergen, Food, Walleye Pike IgE',
    'Allergen, Food, Walnut (Juglans spp.) IgE',
    'Allergen, Food, Walnut IgG',
    'Allergen, Food, Watermelon IgE',
    'Allergen, Food, Wheat',
    'Allergen, Food, Wheat IgG',
    'Allergen, Food, Whey IgE',
    'Allergen, Food, Whey IgG',
    'Allergen, Food, White Pollock IgE',
    'Allergen, Food, Whitefish IgE',
    'Allergen, Food, Whole Egg, IgG',
    'Allergen, Food, Yam IgE',
    'Allergen, Food, Zucchini IgE',
    'Allergen, Fungi and Molds, Alternaria alternata (tenuis)',
    'Allergen, Fungi and Molds, Alternaria tenuis IgG',
    'Allergen, Fungi and Molds, Aspergillus flavus IgE',
    'Allergen, Fungi and Molds, Aspergillus fumigatus',
    'Allergen, Fungi and Molds, Aspergillus fumigatus IgG',
    'Allergen, Fungi and Molds, Aspergillus niger IgE',
    'Allergen, Fungi and Molds, Aureobasidium pullulans',
    'Allergen, Fungi and Molds, Aureobasidium pullulans IgG',
    'Allergen, Fungi and Molds, Bermuda Grass Smut IgE',
    'Allergen, Fungi and Molds, Bipolaris spicifera (Curvularia) IgE',
    'Allergen, Fungi and Molds, Botrytis cinerea IgE',
    'Allergen, Fungi and Molds, Candida albicans',
    'Allergen, Fungi and Molds, Candida albicans IgG',
    'Allergen, Fungi and Molds, Cephalosporium',
    'Allergen, Fungi and Molds, Chaetomium globosum IgE',
    'Allergen, Fungi and Molds, Cladosporium IgG',
    'Allergen, Fungi and Molds, Corn Smut IgE',
    'Allergen, Fungi and Molds, Curvularia lunata',
    'Allergen, Fungi and Molds, Epicoccum',
    'Allergen, Fungi and Molds, Epidermophyton floccosum IgE',
    'Allergen, Fungi and Molds, Fusarium moniliforme',
    'Allergen, Fungi and Molds, Fusarium proliferatum/moniliforme IgG',
    'Allergen, Fungi and Molds, Fusarium solani IgE',
    'Allergen, Fungi and Molds, Helminthosporium',
    'Allergen, Fungi and Molds, Helminthosporium halodes/Setomelanomma rostrata IgG',
    'Allergen, Fungi and Molds, Hormodendrum (Cladosporium)',
    'Allergen, Fungi and Molds, Johnson Grass Smut IgE',
    'Allergen, Fungi and Molds, Mucor racemosus',
    'Allergen, Fungi and Molds, Mucor racemosus IgG',
    'Allergen, Fungi and Molds, Oat Smut IgE',
    'Allergen, Fungi and Molds, Penicillium chrysogenum/notatum IgG',
    'Allergen, Fungi and Molds, Penicillium notatum',
    'Allergen, Fungi and Molds, Phoma betae',
    'Allergen, Fungi and Molds, Phoma betae IgG',
    'Allergen, Fungi and Molds, Pityrosporum orbiculare/Malassezia IgE',
    'Allergen, Fungi and Molds, Rhizopus nigricans',
    'Allergen, Fungi and Molds, Rhizopus nigricans IgG',
    'Allergen, Fungi and Molds, Staphylococcal Enterotoxin A IgE',
    'Allergen, Fungi and Molds, Staphylococcal Enterotoxin B IgE',
    'Allergen, Fungi and Molds, Stemphylium botryosum',
    'Allergen, Fungi and Molds, Stemphylium solani IgE',
    'Allergen, Fungi and Molds, Trichoderma viride IgE',
    'Allergen, Fungi and Molds, Trichophyton mentagrophytes, Interdigitale Variant',
    'Allergen, Fungi and Molds, Trichophyton rubrum IgG',
    'Allergen, Grass, Alfalfa IgE',
    'Allergen, Grass, Bahia',
    'Allergen, Grass, Bent Grass/Redtop Grass',
    'Allergen, Grass, Bermuda',
    'Allergen, Grass, Brome Grass',
    'Allergen, Grass, Canary Grass',
    'Allergen, Grass, Common Reed IgE',
    'Allergen, Grass, Cultivated Barley Pollen IgE',
    'Allergen, Grass, Cultivated Corn Pollen',
    'Allergen, Grass, Cultivated Oat Pollen',
    'Allergen, Grass, Cultivated Wheat Pollen',
    'Allergen, Grass, Johnson Grass',
    'Allergen, Grass, June Grass/Kentucky Bluegrass',
    'Allergen, Grass, Meadow Fescue',
    'Allergen, Grass, Orchard Grass/Cocksfoot',
    'Allergen, Grass, Perennial Rye Grass',
    'Allergen, Grass, Salt Grass IgE',
    'Allergen, Grass, Sweet Vernal Grass',
    'Allergen, Grass, Timothy Grass',
    'Allergen, House Dust Greer',
    'Allergen, House Dust Stier',
    'Allergen, Insect and Venom, Bumble Bee Venom IgE',
    'Allergen, Insect, Mosquito, IgE',
    'Allergen, Insects and Venom, Cockroach, American',
    'Allergen, Insects and Venom, Cockroach, German',
    'Allergen, Insects and Venom, Fire Ant, Imported',
    'Allergen, Insects and Venom, Honey Bee IgE',
    'Allergen, Insects and Venom, Honey Bee IgG',
    'Allergen, Insects and Venom, Paper Wasp',
    'Allergen, Insects and Venom, Paper Wasp IgG',
    'Allergen, Insects and Venom, White-Faced Hornet',
    'Allergen, Insects and Venom, White-Faced Hornet IgG',
    'Allergen, Insects and Venom, Yellow Hornet IgG',
    'Allergen, Insects and Venom, Yellow Jacket IgG',
    'Allergen, Insects and Venom, Yellow Jacket Venom',
    'Allergen, Insects and Venom, Yellow-Faced Hornet',
    'Allergen, Mites, Acarus siro IgE',
    'Allergen, Mites, B. tropicalis',
    'Allergen, Mites, D. farinae',
    'Allergen, Mites, D. microceras IgE',
    'Allergen, Mites, D. pteronyssinus',
    'Allergen, Mites, Euroglyphus maynei IgE',
    'Allergen, Mites, Glycyphagus domesticus IgE',
    'Allergen, Mites, Lepidoglyphus destructor',
    'Allergen, Mites, Tyrophagus putrescentiae IgE',
    'Allergen, Occupational, Cotton Seed IgE',
    'Allergen, Occupational, Ethylene Oxide IgE',
    'Allergen, Occupational, Formaldehyde IgE',
    'Allergen, Occupational, Gum Carageenan IgE',
    'Allergen, Occupational, Isocyanate HDI',
    'Allergen, Occupational, Isocyanate MDI',
    'Allergen, Occupational, Isocyanate TDI',
    'Allergen, Occupational, Latex IgE, Enhanced',
    'Allergen, Occupational, Phthalic Anhydride IgE',
    'Allergen, Occupational, Tobacco',
    'Allergen, Parasite, Ascaris',
    'Allergen, Stemphylium herbarum/botryosum, IgG',
    'Allergen, Tomato IgG',
    'Allergen, Tree, Acacia Tree',
    'Allergen, Tree, Alder Tree',
    'Allergen, Tree, American Beech Tree',
    'Allergen, Tree, Arizona Cypress IgE',
    'Allergen, Tree, Aspen IgE',
    'Allergen, Tree, Bald Cypress IgE',
    'Allergen, Tree, Bayberry IgE',
    'Allergen, Tree, Birch Tree',
    'Allergen, Tree, Black Locust IgE',
    'Allergen, Tree, Black Willow IgE',
    'Allergen, Tree, Box Elder/Maple Tree',
    'Allergen, Tree, California Pepper IgE',
    'Allergen, Tree, Cedar/Red Tree',
    'Allergen, Tree, Cottonwood Tree',
    'Allergen, Tree, Douglas Fir IgE',
    'Allergen, Tree, Elm Tree',
    'Allergen, Tree, Eucalyptus Tree',
    'Allergen, Tree, Groundsel IgE',
    'Allergen, Tree, Hackberry IgE',
    'Allergen, Tree, Hazelnut IgE',
    'Allergen, Tree, Hickory Shagbark IgE',
    'Allergen, Tree, Italian Cypress IgE',
    'Allergen, Tree, Japanese Cedar Tree',
    'Allergen, Tree, Maple Sugar IgE',
    'Allergen, Tree, Melaleuca Tree IgE',
    'Allergen, Tree, Mesquite Tree',
    'Allergen, Tree, Mountain Cedar (Juniper) Tree',
    'Allergen, Tree, Mulberry Red IgE',
    'Allergen, Tree, Oak Red IgE',
    'Allergen, Tree, Oak Tree',
    'Allergen, Tree, Olive Tree',
    'Allergen, Tree, Palm/Queen Tree IgE',
    'Allergen, Tree, Pecan (White Hickory) Tree',
    'Allergen, Tree, Pine/Australian Tree',
    'Allergen, Tree, Poplar White IgE',
    'Allergen, Tree, Privet Tree',
    'Allergen, Tree, Sweet Gum Tree',
    'Allergen, Tree, Sycamore Tree',
    'Allergen, Tree, Virginia Live Oak Tree',
    'Allergen, Tree, Walnut Tree',
    'Allergen, Tree, White Ash Tree',
    'Allergen, Tree, White Mulberry Tree',
    'Allergen, Tree, White Pine Tree',
    'Allergen, Tree, Willow Tree',
    'Allergen, Weed, Careless Weed IgE',
    'Allergen, Weed, Cocklebur',
    'Allergen, Weed, Common/Short Ragweed',
    'Allergen, Weed, Dandelion',
    'Allergen, Weed, Dog Fennel IgE',
    'Allergen, Weed, English Plantain',
    'Allergen, Weed, False Ragweed',
    'Allergen, Weed, Giant Ragweed',
    'Allergen, Weed, Goldenrod',
    'Allergen, Weed, Kochia/Firebush',
    'Allergen, Weed, Lamb\'s Quarters',
    'Allergen, Weed, Marsh Elder',
    'Allergen, Weed, Mugwort',
    'Allergen, Weed, Nettle',
    'Allergen, Weed, Pigweed',
    'Allergen, Weed, Russian Thistle',
    'Allergen, Weed, Sagebrush/Wormwood',
    'Allergen, Weed, Scale',
    'Allergen, Weed, Sheep Sorrel',
    'Allergen, Weed, Sunflower Pollen IgE',
    'Allergen, Weed, Wall pellitory (P. officinalis)',
    'Allergen, Weed, Western Ragweed',
    'Allergen, Weed, Western Waterhemp (Amaranthus spp.) IgE',
    'Allergen, Weed, Wingscale (Atriplex canescens) IgE',
    'Allergen, Weed, Yellow Dock (Rumex crispus) IgE',
    'Allergens, Additional Molds Profile IgE',
    'Allergens, Animal Epithelium/Dander/Feather Mix Profile',
    'Allergens, Animal, Dog/Cat Epithelium Profile',
    'Allergens, Dust/Mite Profile',
    'Allergens, Food, Cereal Profile',
    'Allergens, Food, Common Adult Food IgE',
    'Allergens, Food, Common Panel IgG',
    'Allergens, Food, Comprehensive Profile 1',
    'Allergens, Food, Egg Components IgE',
    'Allergens, Food, Extended Panel IgG',
    'Allergens, Food, Fish Profile IgE',
    'Allergens, Food, IgG Panel',
    'Allergens, Food, Meat Panel IgG',
    'Allergens, Food, Nut Mix Profile',
    'Allergens, Food, Nuts',
    'Allergens, Food, Profile 10',
    'Allergens, Food, Profile 13',
    'Allergens, Food, Profile 19',
    'Allergens, Food, Profile 4',
    'Allergens, Food, Profile 8',
    'Allergens, Food, Profile 9',
    'Allergens, Food, Salad Profile',
    'Allergens, Food, Seafood Profile',
    'Allergens, Food, Shell Fish Profile',
    'Allergens, Food, Southeast Profile',
    'Allergens, Food, Southwest Basic Profile',
    'Allergens, Food, Vegetable Profile IgE',
    'Allergens, Food, West Kentucky Group',
    'Allergens, Foods, Common 10',
    'Allergens, Grass Profile',
    'Allergens, Hymenoptera, Bee Venom Profile',
    'Allergens, Inhalant Multiallergen IgE, Qualitative',
    'Allergens, Inhalants Panel 11 IgE',
    'Allergens, Inhalants, California Environmental',
    'Allergens, Inhalants, California Pollen',
    'Allergens, Inhalants, Comprehensive Profile 2',
    'Allergens, Inhalants, Comprehensive Profile IgE',
    'Allergens, Inhalants, Environmental Profile 10',
    'Allergens, Inhalants, Indoor',
    'Allergens, Inhalants, Midwest Comprehensive 1',
    'Allergens, Inhalants, Midwest Comprehensive 2',
    'Allergens, Inhalants, Northeast Comprehensive',
    'Allergens, Inhalants, Profile 13 IgE',
    'Allergens, Inhalants, Profile 18 IgE',
    'Allergens, Inhalants, Profile 28 IgE',
    'Allergens, Inhalants, Southeast Coastal Comprehensive',
    'Allergens, Inhalants, Southern California Profile',
    'Allergens, Inhalants, Southwest Basic',
    'Allergens, Inhalants, Southwest Comprehensive 1',
    'Allergens, Inhalants, Southwest Comprehensive 2',
    'Allergens, Inhalants, Southwest Extended Profile',
    'Allergens, Inhalants, Southwest Valley Profile',
    'Allergens, Inhalants, Western Environmental IgE',
    'Allergens, Inhalants/Foods, Comprehensive Profile 1',
    'Allergens, Inhalants/Foods, Comprehensive Profile 2',
    'Allergens, Inhalants/Foods, Environmental Profile',
    'Allergens, Inhalants/Foods, Pacific Northwest Profile',
    'Allergens, Inhalants/Foods, Profile A',
    'Allergens, Inhalants/Foods, Southeast Profile',
    'Allergens, Inhalants/Foods, Western Allergy Profile',
    'Allergens, Isocyanate Panel',
    'Allergens, Latex/Cross-Reactive Food Panel IgE',
    'Allergens, Mold Profile',
    'Allergens, Mold Profile, Southeast Comprehensive',
    'Allergens, Pediatric Allergy, March (Progression) Profile IgE',
    'Allergens, Pediatric Foods Profile 1',
    'Allergens, Pediatric Foods/Inhalants Profile',
    'Allergens, Pediatric Inhalants, Southwest',
    'Allergens, Pediatric Profile IgE',
    'Allergens, Respiratory IgE Panel, Region 1, North Atlantic (CT, MA, NJ, PA, VT, ME, NH, NY, RI)',
    'Allergens, Respiratory Panel, Region 10, Southwestern Grasslands (OK, TX) IgE',
    'Allergens, Respiratory Panel, Region 11, Rocky Mountain (AZ, ID, NM, WY CO, MT, UT) IgE',
    'Allergens, Respiratory Panel, Region 12, Arid Southwest (S. AZ, S.E. CA) IgE',
    'Allergens, Respiratory Panel, Region 13, Southern Coastal (CA) IgE',
    'Allergens, Respiratory Panel, Region 14, Central California (CA) IgE',
    'Allergens, Respiratory Panel, Region 15, Intermountain West (NV, S. ID) IgE',
    'Allergens, Respiratory Panel, Region 16, Inland Northwest (OR, Central and East WA) IgE',
    'Allergens, Respiratory Panel, Region 17, Pacific Northwest (NW CA, W. OR, WA) IgE',
    'Allergens, Respiratory Panel, Region 18, Alaska IgE',
    'Allergens, Respiratory Panel, Region 19, Puerto Rico IgE',
    'Allergens, Respiratory Panel, Region 2, Mid-Atlantic (DE, MD, VA, DC, NC) IgE',
    'Allergens, Respiratory Panel, Region 20, Hawaii IgE',
    'Allergens, Respiratory Panel, Region 3, South Atlantic (GA, SC, N. FL) IgE',
    'Allergens, Respiratory Panel, Region 4, Subtropic Florida (S. of Orlando) IgE',
    'Allergens, Respiratory Panel, Region 5, Ohio Valley (IN, OH, TN, WV, KY) IgE',
    'Allergens, Respiratory Panel, Region 6, South Central (AL, AR, LA, MS) IgE',
    'Allergens, Respiratory Panel, Region 7, Northern Midwest (MI, WI, MN) IgE',
    'Allergens, Respiratory Panel, Region 8, Central Midwest (IL, MO, IA) IgE',
    'Allergens, Respiratory Panel, Region 9, Great Plains (KS, NE, ND, SD) IgE',
    'Allergens, Staphylococcal aureus Panel IgE',
    'Allergens, Tree Profile',
    'Allergens, Tree Profile 4',
    'Allergens, Tree, Southeast Profile',
    'Allergens, Upper Respiratory Disease Profile, Region 9A',
    'Allergens, Weed Profile',
    'Allergens, Weed Profile 5',
    'Allergens, Weeds, Southeast Basic Profile',
    'Allergic Bronchopulmonary Aspergillosis (ABPA) Panel',
]