export const typeTests = [
    {
        title: 'Featured Tests',
        items: [
            '17-Ketosteroids, Urine',
            '1p/19q Deletion by FISH',
            '5\'Nucleotidase, Serum',
            '5-Fluorouracil (5-FU) Toxicity and Chemotherapeutic Response, 5 Mutations',
            '5-Hydroxyindoleacetic Acid (HIAA), Urine',
            'Acid Hemolysin (Ham Test)Paroxysmal Nocturnal Hemoglobinuria (PNH)',
            'Acute Lymphocytic Leukemia (ALL) Panel by FISH, Adult',
            'Acute Lymphocytic Leukemia (ALL) Panel by FISH, Pediatric',
            'Acute Myelogenous Leukemia (AML) with Myelodysplastic Syndrome (MDS), or Therapy-Related AML, by FISH',
            'Acute Myelogenous Leukemia Panel by FISH',
            'Adrenocorticotropic Hormone (ACTH) by Immunohistochemistry',
            'Adrenocorticotropic Hormone, Plasma',
            'Pan Cytokeratin (AE1,3) by Immunohistochemistry',
            'Aggressive B-Cell Lymphoma FISH Reflex, Tissue',
            'ALK (D5F3) by Immunohistochemistry with Reflex to ALK Gene Rearrangements by FISH',
            'ALK (D5F3) with Interpretation by Immunohistochemistry',
            'ALK Gene Rearrangements in NSCLC for Crizotinib Eligibility by FISH',
            'Alkaline Phosphatase Isoenzymes, Serum or Plasma',
            'Alkaline Phosphatase, Serum or Plasma',
            'Alpha Fetoprotein, Plasma or Serum (Tumor Marker)',
            'Alpha Fetoprotein, Total and L3 Percent',
            'Alpha-1-Antichymotrypsin (A1ACT) by Immunohistochemistry',
            'Alpha-1-Fetoprotein (AFP) by Immunohistochemistry',
            'Anaplastic Lymphoma Kinase 1 (ALK-1) by Immunohistochemistry',
            'Angiotensin Converting Enzyme, Serum',
            'Arginase 1 by Immunohistochemistry',
            'Arginine Vasopressin Hormone, Plasma',
            'B Cell Specific Octamer Binding Protein-1 (BOB-1) by Immunohistochemistry',
            'B-Cell CD20 Expression',
            'B-Cell Clonality Screening (IgH and IgK) by PCR',
            'BCL-2 by Immunohistochemistry',
            'BCL-6 by Immunohistochemistry',
            'BCR-ABL1 Mutation Analysis by Next Generation Sequencing',
            'BCR-ABL1, Major (p210), Quantitative',
            'BCR-ABL1, Minor (p190), Quantitative',
            'BCR-ABL1, Qualitative with Reflex to BCR-ABL1 Quantitative',
            'Bence Jones Protein, Qualitative Free Kappa and Lambda Light Chains, Urine',
            'Bence Jones Protein, Quantitative Free Kappa and Lambda Light Chains, Urine',
            'Anti-Human Epithelial Antigen, Ber-EP4 by Immunohistochemistry',
            'Beta-2 Microglobulin, Serum or Plasma',
            'Beta-Catenin-1 by Immunohistochemistry',
            'Beta-hCG, Serum Quantitative (Tumor Marker)',
            'BF-1 by Immunohistochemistry',
            'Bladder Tumor Associated Antigen',
            'Bone Marrow Failure Sequencing, 35 Genes',
            'Bone Marrow, Chromosome Analysis with Reflex to Genomic Microarray',
            'Bone Specific Alkaline Phosphatase, Serum',
            'BRAF codon 600 Mutation Detection by Pyrosequencing',
            'BRAF Codon 600 Mutation Detection with Reflex to MLH1 Promoter Methylation',
            'BRAF V600E Mutation Detection in Circulating Cell-Free DNA by Digital Droplet PCR',
            'BRAF V600E Mutation Detection in Hairy Cell Leukemia by Real-Time PCR, Quantitative',
            'Breast 2 (GCDFP-15) by Immunohistochemistry',
            'Breast and Ovarian Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 20 Genes',
            'Breast and Ovarian Hereditary Cancer Syndrome (BRCA1 and BRCA2) Sequencing',
            'Breast and Ovarian Hereditary Cancer Syndrome (BRCA1 and BRCA2) Sequencing and Deletion/Duplication',
            'Breast Carcinoma b72.3 by Immunohistochemistry',
            'c-MET by Immunohistochemistry',
            'C-MYC by Immunohistochemistry',
            'C-Peptide, Serum or Plasma',
            'Calcitonin by Immunohistochemistry',
            'Calcitonin, Serum or Plasma',
            'Caldesmon by Immunohistochemistry',
            'CALR (Calreticulin) Exon 9 Mutation Analysis by PCR',
            'Calretinin by Immunohistochemistry',
            'Cancer Antigen 125 by Immunohistochemistry',
            'Cancer Antigen 125, Serum or Plasma',
            'Cancer Antigen 27.29, Serum',
            'Cancer Antigen-Breast (CA 15-3), Serum or Plasma',
            'Cancer Antigen-GI (CA 19-9), Body Fluid',
            'Cancer Antigen-GI (CA 19-9), Serum or Plasma',
            'Cancer Panel, Hereditary, Deletion/Duplication, 46 Genes',
            'Cancer Panel, Hereditary, Sequencing and Deletion/Duplication, 47 Genes',
            'Carcinoembryonic Antigen, Fluid',
            'Carcinoembryonic Antigen, Monoclonal (CEA M) by Immunohistochemistry',
            'Carcinoembryonic Antigen, Polyclonal (CEA P) by Immunohistochemistry',
            'Carcinoembryonic Antigen, Serum',
            'Carotenes, Fractionated, Plasma or Serum',
            'Catecholamines Fractionated by LC-MS/MS, Urine Free',
            'Catecholamines Fractionated, Plasma',
            'CBFB-MYH11 inv(16) Detection, Quantitative',
            'CD10 (CALLA) by Immunohistochemistry',
            'CD117 (c-Kit) by Immunohistochemistry',
            'CD138 (Syndecan-1) by Immunohistochemistry',
            'CD14 by Immunohistochemistry',
            'CD15, Leu M1 by Immunohistochemistry',
            'CD19 by Immunohistochemistry',
            'CD1a by Immunohistochemistry',
            'CD2 by Immunohistochemistry',
            'CD20, L26 by Immunohistochemistry',
            'CD21 (Dendritic Cell) by Immunohistochemistry',
            'CD23 by Immunohistochemistry',
            'CD25 by Immunohistochemistry',
            'CD3 by Immunohistochemistry',
            'CD30 (Ki-1) by Immunohistochemistry',
            'CD33 by Immunohistochemistry',
            'CD34, QBEnd/10 by Immunohistochemistry',
            'CD35 by Immunohistochemistry',
            'CD4 by Immunohistochemistry',
            'CD42b by Immunohistochemistry',
            'CD43, L60 (Leu 22) by Immunohistochemistry',
            'CD44 by Immunohistochemistry',
            'CD45 by Immunohistochemistry',
            'CD5 by Immunohistochemistry',
            'CD52 (CAMPATH-1) by Immunohistochemistry',
            'CD56 (NCAM) by Immunohistochemistry',
            'CD57 by Immunohistochemistry',
            'CD61 (Platelet Glycoprotein IIIA) by Immunohistochemistry',
            'CD68, KP1 by Immunohistochemistry',
            'CD7 by Immunohistochemistry',
            'CD79A by Immunohistochemistry',
            'CD8 by Immunohistochemistry',
            'CDK4 by Immunohistochemistry',
            'CDX2 by Immunohistochemistry',
            'CEBPA Mutation Detection',
            'Central Nervous System Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 15 Genes',
            'Chromogranin A by Immunohistochemistry',
            'Chromogranin A, Serum',
            'Chromosome Analysis, Bone Marrow',
            'Chromosome Analysis, Leukemic Blood',
            'Chromosome Analysis, Peripheral Blood',
            'Chromosome Analysis, Solid Tumor',
            'Chromosome FISH, CLL Panel',
            'Chromosome FISH, Interphase',
            'Chromosome FISH, Multiple Myeloma Panel Process and Hold',
            'Circulating Tumor Cell Count',
            'Colon Cancer Gene Panel, Somatic',
            'Creatine Kinase Isoenzymes, Serum',
            'CXCL13 by Immunohistochemistry',
            'Cyclic AMP, Urine',
            'Cyclin D1, SP4 by Immunohistochemistry',
            'Cytochrome P450 2C19, CYP2C19 - 9 Variants',
            'Cytochrome P450 2C9, CYP2C9 - 2 Variants',
            'Cytochrome P450 2D6 (CYP2D6) 14 Mutations and Gene Duplication',
            'Cytochrome P450 Genotype Panel',
            'Cytogenomic Molecular Inversion Probe Array, Copy Number and Heterozygosity Assessment - Formalin-Fixed Paraffin-Embedded (FFPE) Tissue',
            'Cytogenomic SNP Microarray—Oncology',
            'Cytokeratin 19 (CK 19) by Immunohistochemistry',
            'Cytokeratin 19 Fragment (CYFRA 21-1), Serum',
            'Cytokeratin 20 (CK 20) by Immunohistochemistry',
            'Cytokeratin 5,6 (CK 5,6) by Immunohistochemistry',
            'Cytokeratin 7 (CK 7) by Immunohistochemistry',
            'Cytokeratin 8,18 Low Molecular Weight (CAM 5.2) by Immunohistochemistry',
            'Cytokine Panel 12 by MAFD, Serum or Plasma',
            'Cytology, Fine Needle Aspirate',
            'Cytology, Non-Gynecologic',
            'Cytology, SurePath Liquid-Based Pap',
            'Cytology, SurePath Liquid-Based Pap Test and Human Papillomavirus (HPV), High Risk by Hybrid Capture (for routine co-testing in women over 30)',
            'Cytology, SurePath Liquid-Based Pap Test with Reflex to Human Papillomavirus (HPV) DNA Probe, High Risk',
            'Cytology, ThinPrep Pap Test and Human Papillomavirus (HPV), High Risk, E6/E7 mRNA by Transcription-Mediated Amplification (TMA)',
            'Cytology, ThinPrep® Pap Test',
            'Cytology, ThinPrep® Pap Test with Reflex to Human Papillomavirus (HPV), High Risk, E6/E7 mRNA by Transcription-Mediated Amplification (TMA)',
            'Cytomegalovirus Antibody, IgG, Serum',
            'D2-40 by Immunohistochemistry',
            'DDIT3 (CHOP) (12q13) Gene Rearrangement by FISH',
            'Dehydroepiandrosterone Sulfate, Serum or Plasma',
            'Des-gamma-carboxy Prothrombin, Serum',
            'Desmin by Immunohistochemistry',
            'Dihydropyrimidine Dehydrogenase (DPYD) Genotyping, 3 Mutations',
            'DNA Content/Cell Cycle Analysis, Miscellaneous',
            'DOG1 by Immunohistochemistry',
            'E-Cadherin by Immunohistochemistry',
            'EGFR by FISH',
            'EGFR Mutation Detection by Pyrosequencing',
            'EGFR T790M Mutation Detection in Circulating Cell-Free DNA by Digital Droplet PCR',
            'EIF2AK4-Associated Disorders (EIF2AK4) Sequencing',
            'Endocrine Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 13 Genes',
            'Eosinophilia Panel by FISH',
            'Epi proColon',
            'Epithelial Membrane Antigen (EMA) by Immunohistochemistry',
            'Epithelial-related Antigen, MOC-31 by Immunohistochemistry',
            'Epstein-Barr Virus (EBV) by in situ Hybridization, Paraffin',
            'Epstein-Barr Virus, Quantitative PCR',
            'ERBB2 (HER-2/neu) Gene Amplification by FISH, Tissue',
            'ERBB2 (HER2)(HercepTest) by Immunohistochemistry',
            'ERBB2 (HercepTest®) by Immunohistochemistry, Tissue with Reflex to FISH if 2+',
            'ERBB2 (HercepTest®) with Interpretation by Immunohistochemistry, Tissue',
            'Erythropietin, Serum or Plasma',
            'Esterase Stain, Nonspecific',
            'Estradiol, Serum, Adult Premenopausal Female, Serum or Plasma',
            'Estrogen Receptor (ER) by Immunohistochemistry',
            'Estrogen/Progesterone Receptor with Interpretation by Immunohistochemistry',
            'Ewing Sarcoma (O13) by Immunohistochemistry',
            'EWSR1 (22q12) Gene Rearrangement by FISH',
            'Factor XIIIa by Immunohistochemistry',
            'Familial Adenomatous Polyposis (APC) Sequencing',
            'Familial Adenomatous Polyposis Panel: APC Sequencing, APC Deletion/Duplication, and MYH 2 Mutations',
            'Familial Mutation, Targeted Sequencing',
            'FLT3 Mutation Detection by PCR',
            'FLT3 Signal Ratio Mutation Detection by PCR',
            'Follicle Stimulating Hormone, Serum',
            'FOXO1 (FKHR) (13q14) Gene Rearrangement by FISH',
            'Friend Leukemia Integration-1 (Fli-1) by Immunohistochemistry',
            'Gastrin by Immunohistochemistry',
            'Gastrin, Serum',
            'Gastrointestinal Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 16 Genes',
            'Gastrointestinal Stromal Tumor Mutation',
            'Glial Fibrillary Acidic Protein (GFAP) by Immunohistochemistry',
            'Glucagon, Plasma',
            'Glucose-6-Phosphate Dehydrogenase',
            'Glypican 3 by Immunohistochemistry',
            'Granzyme B by Immunohistochemistry',
            'Growth Hormone, Serum or Plasma',
            'HBME-1 (Mesothelial Cell) by Immunohistochemistry',
            'Helicobacter pylori by Immunohistochemistry',
            'Hepatocellular Carcinoma Tumor Marker Panel',
            'Hepatocyte Specific Antigen (HSA) by Immunohistochemistry',
            'HER-2/neu Quantitative by ELISA',
            'Hereditary Paraganglioma-Pheochromocytoma (SDHB) Sequencing and Deletion/Duplication',
            'Hereditary Paraganglioma-Pheochromocytoma (SDHB, SDHC, and SDHD) Deletion/Duplication',
            'Hereditary Paraganglioma-Pheochromocytoma (SDHB, SDHC, and SDHD) Sequencing and Deletion/Duplication Panel',
            'Hereditary Paraganglioma-Pheochromocytoma (SDHC) Sequencing and Deletion/Duplication',
            'Hereditary Paraganglioma-Pheochromocytoma (SDHD) Sequencing and Deletion/Duplication',
            'Herpes Virus 8 by Immunohistochemistry',
            'HLA-B*5701 Associated Variant Genotyping for Abacavir Sensitivity',
            'Melanoma Antibody, HMB45 by Immunohistochemistry',
            'HNPCC/Lynch Syndrome (MLH1) Sequencing and Deletion/Duplication',
            'HNPCC/Lynch Syndrome (MSH2) Sequencing and Deletion/Duplication',
            'HNPCC/Lynch Syndrome (MSH6) Sequencing and Deletion/Duplication',
            'HNPCC/Lynch Syndrome (PMS2) Sequencing and Deletion/Duplication',
            'HNPCC/Lynch Syndrome Deletion/Duplication',
            'Homovanillic Acid (HVA), Urine',
            'HRAS Mutation Detection by Pyrosequencing',
            'Human Chorionic Gonadotropin (Beta-hCG) by Immunohistochemistry',
            'Human Epididymis Protein 4 (HE4)',
            'Growth Hormone by Immunohistochemistry',
            'Human Papillomavirus (HPV) 16 and 18 Genotype by PCR, SurePath',
            'Human Papillomavirus (HPV) DNA Probe, High Risk, Cervical Brush',
            'Human Papillomavirus (HPV) Genotypes 16 and 18/45, E6/E7 mRNA by Transcription-Mediated Amplification (TMA)',
            'Human Papillomavirus (HPV) High Risk In Situ Hybridization, Paraffin',
            'Human Papillomavirus (HPV) Low Risk by In Situ Hybridization, Paraffin',
            'Human Papillomavirus (HPV), High Risk by Hybrid Capture (SurePath)',
            'Human Papillomavirus (HPV), High Risk by Hybrid Capture, ThinPrep',
            'Human Papillomavirus (HPV), High Risk by PCR, SurePath',
            'Human Papillomavirus (HPV), High Risk by PCR, ThinPrep',
            'Human Papillomavirus (HPV), High Risk with 16 and 18 Genotype by PCR, SurePath',
            'Human Papillomavirus (HPV), High Risk with 16 and 18 Genotype by PCR, ThinPrep',
            'Human Papillomavirus (HPV), High Risk, E6/E7 mRNA by Transcription-Mediated Amplification (TMA)',
            'Human Papillomavirus (HPV), High Risk, E6/E7 mRNA by Transcription-Mediated Amplification (TMA) with Reflex to Genotypes 16 and 18/45',
            'Human Placental Lactogen (HPL) by Immunohistochemistry',
            'Human T-Lymphotrophic Virus Types I/II Antibodies, Western Blot',
            'Human T-Lymphotropic Virus Types I/II Antibodies with Reflex to HTLV I/II Confirmation',
            'IDH1 and IDH2 Mutation Analysis, exon 4',
            'IDH1 R132H Point Mutation with Interpretation by Immunohistochemistry',
            'IDH1R132H Mutation by Immunohistochemistry',
            'IGF-1 (Insulin-Like Growth Factor 1)',
            'IGH-BCL2 Fusion, t(14;18) by FISH for Detection in Follicular Lymphoma',
            'IGH-CCND1 (BCL-1/JH) Translocation, t(11;14) by PCR',
            'IGH-CCND1 Fusion, t(11;14) by FISH',
            'IGH-MYC Fusion t(8;14) by FISH for Detection in Burkitt Lymphoma',
            'IGHV Mutation Analysis by Sequencing',
            'Immunofixation Electrophoresis Gel',
            'Inhibin A (Dimer), Serum',
            'Inhibin B, Serum',
            'Inhibin by Immunohistochemistry',
            'INI1 (BAF47) by Immunohistochemistry',
            'Insulin, Fasting, Serum or Plasma',
            'Interleukin 28 B (IL28B)—Associated Variants, 2SNPs',
            'MUM1/IRF4 by Immunohistochemistry',
            'JAK2 Exon 12 Mutation Analysis by PCR',
            'JAK2 Gene, V617F Mutation, Qualitative',
            'JAK2 Gene, V617F Mutation, Qualitative with Reflex to CALR (Calreticulin) Exon 9 Mutation Analysis by PCR with Reflex to MPL codon 515 Mutation Detection by Pyrosequencing, Quantitative',
            'JAK2 Gene, V617F Mutation, Qualitative with Reflex to JAK2 Exon 12 Mutation Analysis by PCR',
            'JAK2 Gene, V617F Mutation, Quantitation',
            'Juvenile Polyposis (BMPR1A) Sequencing',
            'Juvenile Polyposis (SMAD4) Deletion/Duplication',
            'Juvenile Polyposis (SMAD4) Sequencing',
            'Juvenile Polyposis (SMAD4) Sequencing and Deletion/Duplication',
            'Juvenile Polyposis Syndrome (BMPR1A) Deletion/Duplication',
            'Kappa Light Chains by Immunohistochemistry',
            'Kappa/Lambda Quantitative Free Light Chains with Ratio, Serum',
            'Keratin 903 (K903) High Molecular Weight by Immunohistochemistry',
            'Ki-67 with Interpretation by Immunohistochemistry',
            'Ki-67, MIB1, by Immunohistochemistry',
            'KIT Mutations in AML by Fragment Analysis and Sequencing',
            'KIT Mutations, Melanoma',
            'KRAS Mutation Detection',
            'KRAS Mutation Detection with BRAF reflex',
            'Lactate Dehydrogenase, Serum or Plasma',
            'Lambda Light Chains by Immunohistochemistry',
            'Leukemia/Lymphoma Phenotyping by Flow Cytometry',
            'Leukemic Blood, Chromosome Analysis with Reflex to Genomic Microarray',
            'Leukocyte Alkaline Phosphatase',
            'Lipid Associated Sialic Acid, Serum',
            'Lung Cancer Panel',
            'Lung Cancer Panel with KRAS',
            'Luteinizing Hormone, Serum',
            'Lymphoma (Aggressive) Panel by FISH',
            'Lysozyme, Urine',
            'Macroprolactin, Serum or Plasma',
            'Mast Cell Tryptase by Immunohistochemistry',
            'MDM2 by Immunohistochemistry',
            'MDM2 Gene Amplification by FISH',
            'Melan A by Immunohistochemistry',
            'Melanoma Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 6 Genes',
            'MET Gene Amplification by FISH',
            'Metanephrines, Plasma (Free)',
            'Methylenetetrahydrofolate Reductase (MTHFR) 2 Mutations',
            'MGMT Methylation Detection by PCR',
            'Microsatellite Instability (MSI), HNPCC/Lynch Syndrome, by PCR',
            'Mismatch Repair by Immunohistochemistry',
            'Mismatch Repair by Immunohistochemistry with Reflex to BRAF Codon 600 Mutation and MLH1 Promoter Methylation',
            'Mismatch Repair by Immunohistochemistry with Reflex to MLH1 Promoter Methylation',
            'MITF by Immunohistochemistry',
            'MLH1 Promoter Methylation, Paraffin',
            'Molar Pregnancy, 16 DNA Markers',
            'Motor and Sensory Neuropathy Evaluation with Immunofixation Electrophoresis and Reflex to Titer and Neuronal Immunoblot',
            'Motor and Sensory Neuropathy Evaluation with Reflex to Titer and Neuronal Immunoblot',
            'Motor Neuropathy Panel',
            'MPL codon 515 Mutation Detection by Pyrosequencing, Quantitative',
            'Muc-1 by Immunohistochemistry',
            'Muc-4 by Immunohistochemistry',
            'Muc-5AC by Immunohistochemistry',
            'Multiple Endocrine Neoplasia Type 2 (MEN2), RET Gene Mutations by Sequencing',
            'Multiple Myeloma Panel by FISH',
            'Muscle-Specific Actin (MSA) by Immunohistochemistry',
            'MUTYH-Associated Polyposis (MUTYH) 2 Mutations',
            'MYC (8q24) Gene Rearrangement by FISH',
            'MYCN (N-MYC) Gene Amplification by FISH',
            'MYD88 L265P Mutation Detection by PCR, Quantitative',
            'Myelodysplastic Syndrome (MDS) Panel by FISH',
            'Myeloid Malignancies Mutation Panel by Next Generation Sequencing',
            'Myeloid Malignancies Somatic Mutation and Copy Number Analysis Panel',
            'Myeloperoxidase (MPO) by Immunohistochemistry',
            'Myeloproliferative Disorders Panel by FISH',
            'Myogenin (Myf4) by Immunohistochemistry',
            'Myoglobin by Immunohistochemistry',
            'Myosin by Immunohistochemistry',
            'Napsin A by Immunohistochemistry',
            'Neurofilament by Immunohistochemistry',
            'Neuron Specific Enolase, CSF',
            'Neuron Specific Enolase, Polyclonal (NSE P) by Immunohistochemistry',
            'Neuron Specific Enolase, Serum',
            'Neuronal Nuclear (Hu, Ri, Yo, and Amphiphysin) Antibodies IgG by Immunoblot',
            'Neuronal Nuclear Antibodies (ANNA) IgG, Immunoblot, Serum',
            'Neuronal Nuclear Antibody (ANNA) IgG by IFA with Reflex to Titer and Immunoblot,',
            'Neuronal Nuclear Antibody (ANNA) Titer IgG by IFA, Serum',
            'Neuronal Nuclei (NeuN) by Immunohistochemistry',
            'NMP22®',
            'NPM1 Mutation by PCR and Fragment Analysis',
            'NRAS Mutation Detection by Pyrosequencing',
            'Octamer Transcription Factor-2 (Oct 2) by Immunohistochemistry',
            'Octamer Transcription Factor-3 and -4 (Oct 3/4) by Immunohistochemistry',
            'Opioid Receptor, Mu (OPRM1) Genotype, 1 Variant',
            'p16 by Immunohistochemistry',
            'p21 (Waf1/Cip 1) by Immunohistochemistry',
            'P504S (AMACR) by Immunohistochemistry',
            'p53 by Immunohistochemistry',
            'p53 with Interpretation by Immunohistochemistry',
            'p63 by Immunohistochemistry',
            'Pancreatic Polypeptide, Serum',
            'Pancreatitis, (PRSS1) Sequencing',
            'Pancreatobiliary FISH',
            'Parathyroid Hormone (PTH) by Immunohistochemistry',
            'Parathyroid Hormone, Intact with Calcium',
            'Parathyroid Hormone, Intact, Serum or Plasma',
            'Parathyroid Hormone-Related Peptide (PTHrP)',
            'Plasma',
            'Whole Blood',
            'Pax-5 by Immunohistochemistry',
            'PAX8 by Immunohistochemistry',
            'PAX8-PPARG Translocations Detection by PCR',
            'PCA3 - Prostate Cancer Biomarker by Transcription-Mediated Amplification',
            'PD-1 by Immunohistochemistry with Interpretation',
            'PD-L1 22C3 pharmaDx by Immunohistochemistry with Interpretation, pembrolizumab (KEYTRUDA)',
            'PD-L1 28-8 pharmDx by Immunohistochemistry with Interpretation, nivolumab (OPDIVO)',
            'Peutz-Jeghers Syndrome (STK11) Deletion/Duplication',
            'Peutz-Jeghers Syndrome (STK11) Sequencing',
            'Peutz-Jeghers Syndrome (STK11) Sequencing and Deletion/Duplication',
            'PIK3CA Mutation Detection',
            'Placental Alkaline Phosphatase (PLAP) by Immunohistochemistry',
            'PML-RARA Translocation, t(15;17) by RT-PCR, Quantitative',
            'PML/RARα Translocation by FISH',
            'Procollagen Type I Intact N-Terminal Propeptide, Serum',
            'Progesterone Receptor (PR) by Immunohistochemistry',
            'Proinsulin',
            'Proinsulin/Insulin Ratio',
            'Prolactin by Immunohistochemistry',
            'Prolactin Macroadenoma, Serum or Plasma',
            'Prolactin, Serum or Plasma',
            'Prosigna Breast Cancer Prognostic Gene Signature',
            'Prostate Specific Antigen by Immunohistochemistry',
            'Prostate Specific Antigen, Complexed',
            'Prostate Specific Antigen, Free Percentage (includes Free PSA and Total PSA), Serum or Plasma',
            'Prostate Specific Antigen, Total - Medicare Screening',
            'Prostate Specific Antigen, Total with Reflex to Free PSA (includes Free',
            'Prostate Specific Antigen, Total, Serum or Plasma',
            'Prostate Specific Antigen, Ultrasensitive, Serum or Plasma',
            'Prostatic Acid Phosphatase',
            'Prostatic Acid Phosphatase (PAP) by Immunohistochemistry',
            'Protein Electrophoresis with Reflex to Immunofixation Electrophoresis Monoclonal Protein Detection, Quantitation and Characterization, IgA, IgG, & IgM, Serum',
            'Protein Electrophoresis, CSF',
            'Protein Gene Product (PGP) 9.5 by Immunohistochemistry',
            'PTEN by Immunohistochemistry',
            'PTEN with Interpretation by Immunohistochemistry',
            'Purkinje Cell Cytoplasmic Antibody by IFA with Reflex to Titer and Immunoblot, Serum',
            'Raji Cell Immune Complex Assay, Serum',
            'RBC Band 3 Protein Reduction in Hereditary Spherocytosis',
            'Renal Hereditary Cancer Panel, Sequencing and Deletion/Duplication, 15 Genes',
            'RET Gene Rearrangements by FISH',
            'RET-CCDC6 and RET-NCOA4 (RET-PTC1 and RET-PTC3) Translocations Detection by PCR',
            'Risk of Ovarian Malignancy Algorithm',
            'ROS1 by FISH',
            'ROS1 with Interpretation by Immunohistochemistry with Reflex to FISH if Equivocal',
            'RUNX1-RUNX1T1 (AML1-ETO) t(8;21) Detection, Quantitative',
            'S-100 Protein by Immunohistochemistry',
            'S-100B Protein, Serum',
            'SDHB with Interpretation by Immunohistochemistry',
            'Sensory Neuropathy Antibody Panel with Reflex to Titer and Neuronal Western Blot',
            'Serotonin, Serum',
            'Serotonin, Whole Blood',
            'Sezary Cell Exam',
            'Smooth Muscle Actin (SMA) by Immunohistochemistry',
            'Solid Tumor Mutation Panel by Next Generation Sequencing',
            'Soluble Mesothelin Related peptides (MESOMARK®), Serum',
            'Somatostatin, Plasma',
            'Special Stain, Periodic Acid-Schiff (PAS)',
            'Squamous Cell Carcinoma Antigen, Serum',
            'SS18 (SYT) (18q11) Gene Rearrangement by FISH',
            'Synaptophysin by Immunohistochemistry',
            'T-Cell Clonality by Flow Cytometry Analysis of TCR V-Beta',
            'T-Cell Clonality by Next Generation Sequencing',
            'T-Cell Clonality Screening by PCR',
            'T-cell Intracytoplasmic Antigen (TIA-1) by Immunohistochemistry',
            'Tartrate-Resistant Acid Phosphatase (TRAP) by Immunohistochemistry',
            'TdT by Immunohistochemistry',
            'Testosterone, Females or Children',
            'Thiopurine Methyltransferase (TPMT) Genotyping, 4 Variants',
            'Thiopurine Methyltransferase, RBC',
            'Thyroglobulin Antibody',
            'Thyroglobulin by Immunohistochemistry',
            'Thyroglobulin by LC-MS/MS, Serum or Plasma',
            'Thyroglobulin, Fine Needle Aspiration (FNA)',
            'Thyroid Stimulating Hormone, Serum or Plasma',
            'Thyroid Transcription Factor (TTF-1) by Immunohistochemistry',
            'Thyroid Translocation and Mutation Panel',
            'Tumor Necrosis Factor, Alpha, Serum or Plasma',
            'UDP Glucuronosyltransferase 1A1 (UGT1A1) Genotyping',
            'Ulex Europaeus Agglutinin 1 (UEA-1) by Immunohistochemistry',
            'UroVysion FISH',
            'Vanillylmandelic Acid (VMA) & Homovanillic Acid (HVA), Urine',
            'Vanillylmandelic Acid (VMA), Urine',
            'Vasoactive Intestinal Peptide, Plasma',
            'Vimentin by Immunohistochemistry',
            'Viscosity, Serum',
            'Vitamin D, 1, 25-Dihydroxy, Serum or Plasma',
            'Warfarin Sensitivity, CYP2C9 & VKORC1, 3 Variants',
            'Wilms Tumor (WT1), N-terminus by Immunohistochemistry',
            'WT1 Mutation Detection by Sequencing',
            'ZAP-70 Analysis by Flow Cytometry',
        ]
    }
]